---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
“You are sad,” the Knight said in an anxious tone: “Let me sing you a song to comfort you.”  
“Is it very long?” Alice asked, for she had heard a good deal of poetry that day.  
“It's long,” said the Knight, “but it's very, very beautiful. Everybody that hears me sing it - either it brings the tears to their eyes, or else -”  
“Or else what?” said Alice, for the Knight had made a sudden pause.  
“Or else it doesn't, you know. The name of the song is called ‘Haddocks' Eyes.’  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
ONCE when the snow of the year was beginning to fall,	  
We stopped by a mountain pasture to say, “Whose colt?”	  
A little Morgan had one forefoot on the wall,	  
The other curled at his breast. He dipped his head	  
And snorted to us. And then we saw him bolt.	 	     

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,   
   Shining with all his might:  
He did his very best to make   
   The billows smooth and bright--   
And this was odd, because it was  
   The middle of the night.  

The moon was shining sulkily,   
   Because she thought the sun  
Had got no business to be there   
   After the day was done--   
“It’s very rude of him," she said,  
   “To come and spoil the fun!”  
   
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I wandered lonely as a cloud   
That floats on high o'er vales and hills,   
When all at once I saw a crowd,   
A host, of golden daffodils;   
Beside the lake, beneath the trees,   
Fluttering and dancing in the breeze.   

Continuous as the stars that shine   
And twinkle on the milky way,   
They stretched in never-ending line   
Along the margin of a bay:   
Ten thousand saw I at a glance,   
Tossing their heads in sprightly dance.   
